import type { Metadata } from 'next';

import { Handjet } from 'next/font/google';

import Header from '@/components/Header';
import './globals.css';

export const metadata: Metadata = {
    description: 'Generated by create next app',
    title: 'Create Next App',
};
const handjet = Handjet({
    display: 'swap',
    fallback: ['system-ui', 'arial'],
    subsets: ['latin'],
    variable: '--font-handjet',
    weight: ['400', '600'],
});

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html className={handjet.variable} lang="en">
            <body>
                <Header />
                {children}
            </body>
        </html>
    );
}
